src/components/StyledText.tsx

**Info:**
example of usage:
```
<Text style={{ ...typography.caption, color: palette.textGrey }}>
Click
<StyledText title=" here " />
to add your first contact
</Text>
```

Create re-usable link (inline text) component

---

src/components/Button.tsx

Create re-usable raised button component

---

screen/wallets/list.js
src/components/InputItem.tsx
src/components/index.tsx

Reusable text input component

---

src/components/TextAreaItem.tsx
src/components/index.tsx
src/styles/typography.tsx
yarn.lock

Reusable textArea component

---

src/screens/MessageScreen.tsx

**Info:**
This PR is just to add the props for images as `Creating wallet` screen is little bit different than other messages screens.

[25-FIX] add style prop for images

---

src/styles/palette.tsx

Gradient fix

---

src/consts/models.tsx
src/screens/TransactionDetailsScreen.tsx
src/screens/index.tsx
src/state/index.ts
src/state/transactions/actions.ts
src/state/transactions/reducer.ts

My intention was to store only transactions that have notes. for storing and transforming all transactions there should be a task for later. If you have a better idea for naming - feel free. I don't like these either.

Store transaction notes

---

src/components/TransactionItem.tsx
src/consts/models.tsx
src/screens/Dashboard/DashboardScreen.tsx
src/screens/Dashboard/TransactionList.tsx
src/state/transactions/reducer.ts

Note on transactions list

---

src/screens/EditTextScreen.tsx
src/screens/ReceiveCoinsScreen.tsx
src/screens/SendCoinsScreen.tsx

https://trello.com/c/nLSGd35T/136-skaner-qr-kodu-nie-czyta-kodu-z-electrum
https://trello.com/c/IhN19tYw/138-flow-receive-coins-klawiatura-po-klikni%C4%99ciu-w-input-amount-powinna-by%C4%87-numeryczna-a-nie-alfabetyczna

Send to electrum wallet and keyboard type fix

---

src/screens/ContactQRCodeScreen.tsx
src/screens/ReceiveCoinsScreen.tsx

Remove "bitcoin" from share (reported bug)

remove bitcoin from address on share

---

.gitignore
README.md

We need to put firebase specific files about google services in order to be able to build the app

Add missing read me about firebase files

---

src/state/wallets/actions.ts

The history of unconfirmed transactions should be displayed

Fix transactions history

---

src/components/InputItem.tsx
src/components/SearchBar.tsx
src/components/TextAreaItem.tsx
src/screens/EditTextScreen.tsx

For future development: Check Edit screens

Keyboard suggestion is not disabled

---

BlueElectrum.js
src/screens/Settings/ElectrumServerScreen.tsx

User can have some trash in async storage, we should be 100% that he will connect to correct domain

Remove reading domain from async storage

---

index.js
loc/index.js

Fix i18n initialization

---

loc/en.js
src/components/WalletCard.tsx
src/screens/Dashboard/DashboarContentdHeader.tsx
src/screens/ReceiveCoinsScreen.tsx

Improvments ux details

---

class/segwit-p2sh-wallet.js
src/screens/Dashboard/DashboardScreen.tsx

* Fix creating p2sh wallet
* Fix deleting wallet

Fix creating/deleting p2sh wallet

---

src/screens/PinFlow/ConfirmTransactionPassword.tsx
src/screens/PinFlow/CreateTransactionPassword.tsx
src/screens/RecoveryTransactionList/RecoveryTransactionListScreen.tsx
src/screens/SendCoinsScreen.tsx

some changes in
Recovery Send
Password input Icon visibility
Send Adress inputs

Fix in UI parts

---

src/screens/ImportWalletScreen.tsx

For now, is blocked Scan QCode and imports from mnemonic if is not name provided

Fix for imports wallets

---

loc/en.js
src/components/WalletCard.tsx
src/components/WalletDropdown.tsx
src/components/WalletItem.tsx
src/consts/text.ts
src/screens/CreateWalletScreen.tsx
src/screens/Dashboard/DashboarContentdHeader.tsx
src/screens/ImportWalletScreen.tsx
src/screens/TransactionDetailsScreen.tsx
src/screens/WalletDetailsScreen.tsx

- All wallets "not allowed" improvements
- Long name wallet fix in

Improvments in wallets

---

src/components/InputItem.tsx
src/consts/models.tsx
src/screens/CreateContactScreen.tsx
src/screens/RecoverySend/RecoverySendScreen.tsx
src/screens/SendCoinsScreen.tsx

Auto Grow Text Input with multiline parameter

TextInput multiline improments

---

src/screens/ImportAuthenticator/ImportAuthenticatorScreen.tsx

Change description or conditions of unlocking scan QR when making Auth

Change description when making Auth

---

src/components/InputItem.tsx
src/components/SearchBar.tsx

Fix UI problems with 
- Inputs [iOS]
- SearchBar [Android]

Fix UI problems with Inputs and SearchBar

---

src/screens/TransactionDetailsScreen.tsx
utils/bitcoin.ts

Ux fix - Transaction list

---

loc/en.js

Bugfix for remove translation

---

class/legacy-wallet.js
loc/es.js
loc/id_ID.js
loc/jp_JP.js
loc/ko_KR.js
loc/pt_PT.js
loc/tr_TR.js
loc/vi_VN.js
loc/zh_cn.js

- add translation
- remove conditional in setTransations() - on request

Fix all wallets blocker translation and for wallets show  

---

src/screens/ImportAuthenticator/ImportAuthenticatorScreen.tsx
src/screens/UnlockTransaction.tsx

Fix behavior in
- imports authenticators
- input visible icons

Fix imports buttons and input behavior

---

src/screens/RecoveryTransactionList/RecoveryTransactionListScreen.tsx

Waiting for the design approve

Refix in checkboxs

---

App.tsx

Enabled support for release healthcheck

Sentry release health enabled

---

package.json
src/api/client.ts
src/api/config.ts
src/api/emailApi.ts
src/api/index.ts
src/api/types.ts
yarn.lock

Some simple basic client to start build

Basic Client API

---

.gitignore
src/components/Header.tsx
src/components/ListItem.tsx
src/components/Mnemonic.tsx
src/components/StyledSwitch.tsx
src/screens/CreateWalletScreen.tsx
src/screens/CreateWalletSuccessScreen.tsx
src/screens/Dashboard/DashboardHeader.tsx
src/screens/ImportWalletChooseTypeScreen.tsx
src/screens/Settings/AdvancedOptionsScreen.tsx
src/screens/Settings/SettingsScreen.tsx
tests/e2e/helpers.ts
tests/e2e/pageObjects/common/Header.ts
tests/e2e/pageObjects/common/MessageScreen.ts
tests/e2e/pageObjects/index.ts
tests/e2e/pageObjects/pages/Settings.ts
tests/e2e/pageObjects/pages/Wallets.ts
tests/e2e/specFiles/wallets.spec.ts

Automated tests of creating and importing wallets of any type
Changes:
- Added `testID` property to the components used during tests
- Added more e2e tests as it's mentioned above

Automated tests of adding wallets

---

.github/pull_request_template.md
README.md

- Adds template for upcoming pull requests
- Updates Readme
@marek-siemieniuk-morawski @aleparty

Added pull request template

---

src/screens/Notifications/ChangeEmailScreen.tsx
src/screens/Notifications/ConfirmEmailScreen.tsx
src/screens/Notifications/NotificationScreen.tsx
src/screens/Notifications/index.tsx
src/state/notifications/actions.ts
src/state/notifications/reducer.ts
src/state/notifications/sagas.ts

Save email in async-storage

---

src/consts/models.tsx
src/navigators/Navigator.tsx
src/navigators/NotificationNavigator.tsx
src/navigators/PasswordNavigator.tsx
src/navigators/index.tsx
src/screens/AddNotificationEmailScreen/AddNotificationEmailScreen.tsx
src/screens/Notifications/ChooseWalletsForNotificationScreen.tsx

New flow for a user who already has a wallet
It is up to Version T&C as will require in this release
no

Reback flow for onboarding

---

README.md

Updated a part about Sentry in README - it was already outdated.

Updated a part about Sentry in README

---

src/helpers/wallets.ts
src/types.d.ts

Get wallet hashed public keys
@Kamill90

Get wallet hashed public keys

---

src/screens/AddNotificationEmailScreen/AddNotificationEmailScreen.tsx
src/screens/ConfirmNotificationCodeScreen/ConfirmNotificationCodeScreen.tsx
src/screens/TermsConditionsScreen.tsx

If user kill app during onboarding will not ask for T&C again

remove createTC

---

jest.config.js
package.json

- Since now, the unit tests fail if given thresholds are exceeded
- Unit tests with coverage measuring are run on pre-commit.

Configured test coverage threshold

---

loc/en.js
src/screens/TermsConditionsScreen.tsx

Add agreement checkboxes for terms and conditions

Add agreement checboxes for tc

---

src/components/Header.tsx
src/screens/AirdropDashboard/AirdropDashboardScreen.tsx
src/screens/AirdropRequirements/AirdropRequirementsScreen.tsx
src/screens/AirdropThankYou/AirdropThankYouScreen.tsx
src/screens/AuthenticatorList/AuthenticatorListScreen.tsx
src/screens/CreateAuthenticatorPublicKey/CreateAuthenticatorPublicKeyScreen.tsx
src/screens/CreateAuthenticatorSuccess/CreateAuthenticatorSuccessScreen.tsx
src/screens/CreateWalletSuccessScreen.tsx
src/screens/EditTextScreen.tsx
src/screens/FilterTransactionsScreen.tsx
src/screens/ImportWalletScreen.tsx
src/screens/IntegrateKeyScreen.tsx
src/screens/Notifications/ChangeEmailScreen.tsx
src/screens/Notifications/ChooseWalletsForNotificationScreen.tsx
src/screens/Notifications/ConfirmEmailScreen.tsx
src/screens/Notifications/NotificationScreen.tsx
src/screens/PinFlow/CreatePinScreen.tsx
src/screens/RecoverySeed/RecoverySeedScreen.tsx
src/screens/Settings/AboutUsScreen.tsx
src/screens/Settings/AdvancedOptionsScreen.tsx
src/screens/Settings/SelectLanguageScreen.tsx
src/screens/Settings/TermsConditionsSettingsScreen.tsx
src/screens/WalletDetailsScreen.tsx

Fix button styles in Android and prevent going back to 'thank you airdrop screens'

---

src/consts/models.tsx
src/helpers/notifications.ts
src/screens/AddNotificationEmailScreen.tsx
src/screens/ConfirmScreen.tsx
src/screens/CreateWalletScreen.tsx
src/screens/ImportWalletScreen.tsx
src/screens/Notifications/ConfirmEmailScreen.tsx
src/screens/Notifications/NotificationScreen.tsx
src/screens/Settings/SettingsScreen.tsx
src/screens/WalletDetailsScreen.tsx

* Fixes navigation going back from settings
* Fixes create and import wallet crash
* Fixes autofocus on onboarding
* Fixes gestures on confirm notifications

Fixes notifications create, import wallet and go back from settingns

---

src/components/CodeInput.tsx
src/consts/models.tsx
src/screens/Notifications/ConfirmEmailScreen.tsx

* allow only code specific signs in code input
* fix missing attempt try in translation 
* fix code input behaviour

Allow only code specific signs in code input

---

src/components/AirdropFloatingButton.tsx
src/screens/Dashboard/DashboardScreen.tsx

Show airdrop is live screen first time user opens app after airdrop is introduced

show airdrop is live on first app run

---

loc/en.js
src/screens/AirdropDashboard/components/AirdropInProgress.tsx
src/screens/AirdropThankYou/AirdropThankYouScreen.tsx

Copy update

---

loc/en.js
src/consts/models.tsx
src/screens/ReceiveCoinsScreen.tsx
src/screens/SendCoinsScreen.tsx

Fix for crash after putting to the big amount in the receive section
Fix for numeric input has an alphanumeric keyboard

Fixes with UI ux

---

src/consts/models.tsx
src/navigators/Navigator.tsx
src/screens/Dashboard/ActionSheet.tsx
src/screens/Notifications/AddNotificationEmailScreen.tsx
src/screens/ReceiveCoinsScreen.tsx

Forcing to unmount AddNotificationEmailScreen when pressing the skip button

onback fix

---

loc/en.js
src/components/InputItem.tsx
src/screens/Notifications/NotificationScreen.tsx
src/screens/PinFlow/CreateTransactionPassword.tsx
src/screens/ReceiveCoinsScreen.tsx

Add notification for non subscribed.
Fix hide password button doesn't work correctly.
Fix issues with a decimal number in receive input

Other UX/UI fix

---

src/components/AirdropStayTuned.tsx
src/screens/AirdropCreateWalletSubscription.tsx

Provides fixes for social share functionalities

Social issues fixes

---

loc/en.js
src/api/emailNotifications/client.ts
src/screens/LocalConfirmNotificationCodeScreen.tsx
src/screens/Notifications/ChooseWalletsForNotificationScreen.tsx
src/screens/Notifications/ConfirmEmailScreen.tsx
src/screens/Notifications/NotificationScreen.tsx
src/state/notifications/actions.ts
src/state/notifications/reducer.ts
src/state/notifications/selectors.ts

Mostly nothing should change for the user. The difference is that the wrong pin number comes from the backend

Trials left error from backend

---

loc/en.js
src/screens/Notifications/NotificationScreen.tsx
src/screens/ReceiveCoinsScreen.tsx

Notification unsubscribe problem on an empty list
Saving a negative number in receive amount crushes

Bugs UI ux fixture

---

src/helpers/airdrop.ts
src/screens/AirdropDashboard/components/AirdropInProgressContent.tsx

fixes balance logic for airdrop carousel elements

wallet balance fixes

---

src/screens/CreateContactScreen.tsx

Validate contact name while typing

Contact name validation

---

ios/Podfile
metro.config.js

- Moved some Pod dependencies to shared
- Fixed `metro.config.js`

Fixed Podfile and loading mocked components

---

class/app-storage.js
ios/Podfile.lock
loc/index.js
package.json
src/helpers/fees.ts
src/helpers/reduxPersist.ts
src/navigators/Navigator.tsx
src/screens/Notifications/AddNotificationEmailScreen.tsx
src/screens/Notifications/UpdateEmailNotificationScreen.tsx
src/screens/WalletDetailsScreen.tsx
src/services/StoreService.ts
tests/integration/Storage.test.js
tests/setup.js
yarn.lock

Update Async storage library, fixes errors on typing an invalid email address.

async storage update, error fix

---

package.json
src/screens/Settings/AboutUsScreen.tsx
yarn.lock

Fix fo "Rate GoldWallet" button has a long response

"Rate GoldWallet" button has a long response

---

src/consts/models.tsx
src/helpers/wallets.ts

Necessary changes to make subscribe endpoint work

address_range added

---

src/screens/Settings/AboutUsScreen.tsx

Hotfix for dynamic bundel

---

src/screens/Settings/AboutUsScreen.tsx

Hot fix for ios in rate feature

Bugfix in goldwallet button rate 

---

loc/en.js
src/helpers/helpers.ts
src/screens/SendCoinsScreen.tsx

Fix small amounts are displayed in scientific notation
Add in Send Flow

Fix small amounts are displayed in scientific notation

---

src/helpers/helpers.ts
src/screens/SendCoinsScreen.tsx

Refix for replacing the comma with a dot

add comma check

---

class/abstract-hd-segwit-p2sh-wallet.js
class/hd-segwit-bech32-wallet.js
src/consts/models.tsx
src/helpers/wallets.ts
utils/crypto.ts

Changes for dynamic value for pubs in crypto utils base on environment

Testnet xpub support for gw

---

src/helpers/DataProcessing.ts

Changing address in send coins view clears earlier set amount / GW

Changing address in send coins view clears earlier set amount / GW

---

src/screens/ImportAuthenticator/ImportAuthenticatorScreen.tsx
src/screens/ImportWalletScreen.tsx

Scan QR code on Import authenticator or Import wallet screen should only fill in seed phrases not proceed

fill textarea on scan

---

src/screens/CreateContactScreen.tsx

Base on  new AC validation is shortness

Handling for not allowed characters in name while adding new contact

---

src/screens/SendCoinsConfirmScreen.tsx

Fix confirm send screen amount display

Fix confirm send screen amount display

---

.env.beta.testnet
.env.testnet
ios/Podfile.lock

Testnet fix and podlock

---

src/screens/CreateContactScreen.tsx

Able to save an address contact without name

Able to save an address contact without name 

---

class/hd-segwit-bech32-wallet.js
package.json
yarn.lock

Fixing neverending processing screen while creating standard hd segwit wallet

cannot create standard HD Segwit fix

---

src/screens/CreateContactScreen.tsx
src/screens/ReceiveCoinsScreen.tsx
src/screens/SendCoinsConfirmScreen.tsx
src/screens/SendTransactionDetailsScreen.tsx
src/types.d.ts

Additional fix in small amounts are displayed in scientific notation
Fix in not allowed characters in name while adding a new contact

Fixes in small amount and address book

---

tests/e2e/actions.ts
tests/e2e/pageObjects/common/ScanQrCodeScreen.ts
tests/e2e/pageObjects/pages/Wallets.ts
tests/e2e/steps.ts

- Adds 'replaceText' func in UI tests to speed up test execution.
@aleparty

Adds replaceText func for UI tests

---

.env.mainnet
.env.testnet
src/helpers/wallets.ts
tests/e2e/gmail.ts
tests/e2e/specFiles/addingWallets/withSubscribingToNotifications.spec.ts
tests/e2e/specFiles/termsConditions.spec.ts

Enable subscribing all wallets except 'Standard P2SH"

legacy wallets fix

---

src/assets/tc/EN.ts
tests/e2e/specFiles/termsConditions.spec.ts

Fixed terms and conditions, added paragraphs where missing, renabled tests

fix(terms): Fixed terms and condtions

---

tests/e2e/specFiles/Transactions/receive.spec.ts
tests/e2e/specFiles/Transactions/send.spec.ts

- Adds extra tests for integer and decimal amount for `receive` and `send`. 
@aleparty

Adds extra tests for integer and decimal amount

---

src/assets/tc/EN.ts

Update for the English version

T&C update content

---

src/screens/Settings/AboutUsScreen.tsx

Allows to rate app only in stores

Rate app fixes

---

class/legacy-wallet.js
class/watch-only-wallet.js

Fix on Frontend problem with subscribing Standard P2SH

Fix on frontend subscription standard p2sh

---

loc/en.js
src/api/emailNotifications/client.ts
src/helpers/wallets.ts
src/screens/LocalConfirmNotificationCodeScreen.tsx
src/screens/Notifications/AddNotificationEmailScreen.tsx
src/state/notifications/selectors.ts

Display only readable errors from the backend

make all errors readable

---

src/api/emailNotifications/client.ts
src/screens/Notifications/ConfirmEmailScreen.tsx
src/screens/Notifications/UpdateEmailNotificationScreen.tsx
src/state/notifications/selectors.ts

Same address error

---

loc/en.js
src/api/emailNotifications/client.ts
src/consts/models.tsx
src/helpers/notifications.ts
src/screens/Notifications/AddNotificationEmailScreen.tsx
src/screens/Notifications/ChooseWalletsForNotificationScreen.tsx
src/screens/Notifications/NotificationScreen.tsx
src/screens/Notifications/UpdateEmailNotificationScreen.tsx
src/screens/Settings/SettingsScreen.tsx
src/screens/WalletDetailsScreen.tsx
src/state/notifications/selectors.ts

Ux fix in subscribe flow in details

---

src/consts/models.tsx
src/screens/Settings/SettingsScreen.tsx
src/screens/Settings/TermsConditionsSettingsScreen.tsx

Omit problem in Settings Screen with default lang use

Fix settings screen choose lang

---

src/screens/SendCoinsConfirmScreen.tsx
src/screens/SendTransactionDetailsScreen.tsx

Fix in sending Screens during authenticate

Fix sign cancel or fast tx with authenticator

---

src/assets/tc/JP.ts

Small fix in lang tc

---

.env.mainnet
loc/es.js
package.json

Change mail api url

---

.env.mainnet

Release conflict before merge to main

---

android/app/build.gradle
ios/GoldWallet-beta.plist
ios/GoldWallet.xcodeproj/project.pbxproj
ios/GoldWallet/Info.plist
ios/GoldWalletDev-Info.plist
ios/GoldWalletStage-Info.plist
package.json

bump version 6.3.0

---

android/app/build.gradle

Fix for missing prod in envs
- [] Checked on iOS

fix(envs) build.gradle missing prod

---

android/app/build.gradle

missing prod in envs
Co-authored-by: Aleksander Partyka <aleksander.partyka@cloudbest.com>

fix(envs) build.gradle missing prod (#697)

---

src/screens/Dashboard/DashboardScreen.tsx
src/screens/Notifications/NotificationScreen.tsx

Fix in notification switch

---

.detoxrc.json
.gitignore
src/screens/CreateAuthenticatorSuccess/CreateAuthenticatorSuccessScreen.tsx
tests/e2e/actions.ts
tests/e2e/pageObjects/pages/Authenticators.ts
tests/e2e/pageObjects/pages/Dashboard.ts
tests/e2e/pageObjects/pages/Wallets.ts
tests/e2e/specFiles/addingWallets/withoutSubscribingToNotifications.spec.ts
tests/e2e/specFiles/addressBook.spec.ts
tests/e2e/specFiles/authenticators.spec.ts
tests/e2e/specFiles/dashboard.spec.ts
tests/e2e/specFiles/settings.spec.ts
tests/e2e/steps.ts

Fix smoke tests - all smoke test (both on android and iOS) should work now
Add dev config for android

[BTCV2-1430]: Fix smoke tests

---

src/consts/models.tsx
src/screens/CreateWalletScreen.tsx
src/screens/CreateWalletSuccessScreen.tsx

Quick fix for P2SH flow in seed phrase

Fix for P2SH flow in seed phrase

---

src/screens/CreateWalletSuccessScreen.tsx

Add subscription mail to flow P2SH

---

src/screens/CreateWalletScreen.tsx
src/screens/CreateWalletSuccessScreen.tsx

Fix missing success screen

---

src/screens/SeedPhraseConfirmScreen/SeedPhraseConfirmScreen.tsx
tests/e2e/actions.ts
tests/e2e/helpers/consts.ts
tests/e2e/pageObjects/common/ConfirmSeedScreen.ts
tests/e2e/pageObjects/pages/Dashboard.ts
tests/e2e/pageObjects/pages/TransactionDetailsScreen.ts
tests/e2e/specFiles/addingWallets/general.spec.ts
tests/e2e/specFiles/addingWallets/withSubscribingToNotifications.spec.ts
tests/e2e/specFiles/addingWallets/withoutSubscribingToNotifications.spec.ts
tests/e2e/specFiles/addressBook.spec.ts
tests/e2e/specFiles/dashboard.spec.ts
tests/e2e/specFiles/onboarding.spec.ts
tests/e2e/specFiles/settings.spec.ts
tests/e2e/specFiles/walletDetails.spec.ts
tests/e2e/steps.ts

This PR fixes all not skipped regression test cases. All of them should work correctly both on iOS and Android.

[BTCV2-1425] Fix regression test cases

---

.env.dev.testnet
android/app/build.gradle

Fixed android build with Codepush

---

src/components/Tags.tsx
src/screens/SeedPhraseConfirmScreen/SeedPhraseConfirmScreen.tsx

Fix spaces between seeds, for small screens less 400 going to display 2 columns instead 3
Add scroll for screens

Add extra space in seeds

---

android/app/build.gradle
ios/GoldWallet.xcodeproj/project.pbxproj
ios/GoldWallet/Info.plist
ios/GoldWalletDev-Info.plist
ios/GoldWalletStage-Info.plist
package.json
yarn.lock

feat(release-6.4.0): added commitzen and bumped to release to 6.4.0

---

package.json
yarn.lock

Reverts bitcoinvault/GoldWallet#735

Revert "fix yarn audit problems"

---

android/app/src/main/res/values/styles.xml
src/components/TextAreaItem.tsx

Forces to override devices darkmode in app
https://stackoverflow.com/questions/57175226/how-to-disable-night-mode-in-my-application-even-if-night-mode-is-enable-in-andr/64339016#64339016

feat(styles.xml) override device dark mode

---

src/components/AirdropFloatingButton.tsx
src/helpers/airdrop.ts
src/screens/AirdropDashboard/AirdropDashboardScreen.tsx
src/screens/AirdropDashboard/components/AirdropInProgress.tsx
src/screens/AirdropDashboard/components/AirdropInProgressContent.tsx
src/screens/AirdropDashboard/components/CommunityAchievementsList.tsx
src/screens/AirdropFinishedWalletDetails/AirdropFinishedWalletDetails.tsx
src/screens/AirdropRequirements/AirdropRequirementsScreen.tsx
src/screens/AirdropThankYou/AirdropThankYouScreen.tsx
src/screens/CreateWalletScreen.tsx
src/state/airdrop/actions.ts
src/state/airdrop/reducer.ts
src/state/airdrop/sagas.ts
src/state/airdrop/selectors.ts

We need move helpers more to selectors (most of them)

Replacing helpers with selectors
