bitcoinvault/GoldWallet

- src/components/Header.tsx
- src/screens/CreateWalletScreen.tsx
- src/screens/WalletDetailsScreen.tsx
Header height is now 38 + statusbar height (20 for Android), which translates to 58 - same like on Matt's designs.
Touchable areas are 38x38. It's still smaller than Apple official recommendation of 44 pixels high, but we're close ;)
> User experience tweaks to Header touchable areas

- loc/en.js
- src/components/Chip.tsx
- src/components/index.tsx
- src/screens/CreateWalletScreen.tsx
- src/screens/CreateWalletSuccessScreen.tsx
- src/styles/palette.tsx
An easter egg: take a look how it was done previously. Every chip was a separate component, without a map.
```
<View style={{ width: 'auto', marginRight: 8, marginBottom: 8 }}>
<Badge
containerStyle={{
backgroundColor: '#f5f5f5',
paddingTop: 6,
paddingBottom: 6,
paddingLeft: 8,
paddingRight: 8,
borderRadius: 4,
}}>
<Text style={{ color: '#81868E', fontWeight: 'bold' }}>1. {this.state.words[0]}</Text>
</Badge>
</View>
```
And copy paste it 24 times :D
> Create wallet success screen with mnemonic passphrase

- class/hd-segwit-bech32-wallet.js
- class/hd-segwit-p2sh-wallet.js
- class/segwit-p2sh-wallet.js
- loc/en.js
- src/consts/models.tsx
- src/navigators/RootNavigator.tsx
- src/navigators/UnlockTransactionNavaigator.tsx
- src/navigators/index.tsx
- src/screens/CreateWalletScreen.tsx
- src/screens/SendCoinsConfirmScreen.tsx
- src/screens/Settings/ElectrumServerScreen.tsx
- src/screens/UnlockScreen.tsx
- src/screens/UnlockTransaction.tsx
- src/screens/index.tsx
5b_dashboard_add_wallet_advanced - zmiana nazwy typu wallet'ów oraz ich opis
5c_dashboard_add_wallet_advanced_error - identyczna zmiana, jak wyżej
40_settings_electrum_server - dodanie nagłówka i opisu do sekcji
45b_advanced_options - dodanie nagłówka i opisu do sekcji
81_transaction_confirm - widok potwierdzenia Transaction Password pojawiający się od razu po próbie przeprocesowania transakcji
82_transaction_confirm_filled - widok potwierdzenia Transaction Password z wypełnionymi danymi. Funkcjonalność podejrzenia hasła w tym widoku, jak i w poprzednim działa identycznie, jak na onboarding'u
> UI adjustments

- src/screens/Settings/SettingsScreen.tsx
A small feature to display network info on the settings screen (for testers). Will be removed before the release. Agreed by @jakubkornafel
> display network info

- tests/e2e/pageObjects/common/MessageScreen.ts
- tests/e2e/pageObjects/pages/Authenticators.ts
Tests are failing in Bitrise on the of step closing a success screen after creating authenticators
Changes:
- Added missing implementation of `waitUntilEnded()`
- Make Detox close keyboard after entering authenticator name on Create Authenticator screen
> Fixed failing Authenticators tests

- .eslintignore
- .gitignore
- App.tsx
- android/app/build.gradle
- android/app/src/main/java/io/goldwallet/wallet/MainApplication.java
- android/settings.gradle
- create-sentry-properties.sh
- ios/GoldWallet-beta.plist
- ios/GoldWallet.xcodeproj/project.pbxproj
- ios/GoldWallet/Info.plist
- package.json
- tsconfig.json
- yarn.lock
- Configured Xcode & Gradle to automatically create a Sentry release, generate sourcemap and upload it while building the app (no extra step necessary since now)
- Added missing Sentry configuration for Android
- Modified `create-sentry-properties.sh` to create three `sentry.properties` files instead of one.
- Upgraded Sentry to 2.1.0
Sentry documentation mainly.
Anybody
> Reconfigured Sentry to create release and upload source map while building the app

- android/app/src/main/java/io/goldwallet/wallet/MainApplication.java
I haven't tested the changes I made on Android at all 🙈 and it turned out there's a bug. The app crashes on start due to duplicated RNSentry module declaration.
Here's the error:
Anybody
> Removed duplicated RNSentry module declaration

- tests/e2e/specFiles/Transactions/send.spec.ts
Removes scroll to transaction note function in `send.specs.ts` to improves the stability of UI tests for transactions.
@marek-siemieniuk-morawski
> Removed func with scroll to transaction note

- src/navigators/RootNavigator.tsx
- src/screens/CreateWalletSuccessScreen.tsx
It fixes the possibility of going back with gestures on iOS on some screen that user shouldn't suppose to do that
> Fix navigation gestures

- src/screens/ImportWalletScreen.tsx
- src/screens/TermsConditionsScreen.tsx
- tests/e2e/pageObjects/pages/TermsConditionsScreen.ts
- tests/e2e/specFiles/termsConditions.spec.ts
Commented out a code that made it impossible to pass through an import flow if email address wasn't added during onboarding.
> Fixed an import flow when email address is not configured yet

- src/consts/models.tsx
- src/screens/EditTextScreen.tsx
- src/screens/ReceiveCoinsScreen.tsx
- tests/e2e/pageObjects/index.ts
- tests/e2e/pageObjects/pages/Transactions/Receive.ts
- tests/e2e/pageObjects/pages/Transactions/Send.ts
- tests/e2e/pageObjects/pages/Wallets.ts
- tests/e2e/specFiles/Transactions/receive.spec.ts
- tests/e2e/specFiles/Transactions/send.spec.ts
- Adds UI tests for receive section in transactions flow.
- Removing typo naming for `tapNextButton()` in `transactions/send`.
@marek-siemieniuk-morawski
> Adds tests for receive section in transactions

- src/helpers/reduxPersist.ts
- src/screens/AddNotificationEmailScreen.tsx
- src/screens/LocalConfirmNotificationCodeScreen.tsx
- src/state/notifications/actions.ts
- src/state/notifications/reducer.ts
- src/state/notifications/selectors.ts
- src/state/rootReducer.ts
- src/state/store.ts
It adds missing loading and errors states for onboarding
Deleted "localError", now errors are taken only from redux so we have a single source of truth.
Notifications state persists only chosen values. We should from now on store explicit values as there is a problem with values that shouldn't be stored, like "isLoading", for example after relaunching the app we can get isLoading true even if no action was fired
https://github.com/rt2zz/redux-persist
> Add loading and error state to onboarding

- error/messages.ts
- src/components/TimeoutButton.tsx
- src/consts/models.tsx
- src/screens/AddNotificationEmailScreen.tsx
- src/screens/CreateWalletScreen.tsx
- src/screens/ImportWalletScreen.tsx
- src/screens/LocalConfirmNotificationCodeScreen.tsx
- src/screens/Notifications/ChooseWalletsForNotificationScreen.tsx
- src/screens/Notifications/ConfirmEmailScreen.tsx
- src/screens/PinFlow/CreatePinScreen.tsx
- src/screens/WalletDetailsScreen.tsx
- src/state/authentication/actions.ts
- src/state/notifications/actions.ts
- src/state/notifications/reducer.ts
- src/state/notifications/sagas.ts
- src/state/notifications/selectors.ts
- src/state/wallets/selectors.ts
* Add resend and error handling for code confirm screen
* Fix wallets details subscription refresh after sub/unsub
* moved failed tries and the error to redux to make it possible to manage the state and get rid of two sources of truth.
* move whole sub/unsub logic to sagas
> Add resend and error handling for code confirm screen

- src/screens/ImportWalletScreen.tsx
Change the notification import wallet flow so the check subscription occurs after importing the wallet
> Fix notification import wallet flow

- src/consts/models.tsx
- src/screens/CreateWalletScreen.tsx
- src/screens/ImportWalletScreen.tsx
- src/screens/Notifications/AddNotificationEmailScreen.tsx
- src/screens/Notifications/ChooseWalletsForNotificationScreen.tsx
- src/screens/Notifications/ConfirmEmailScreen.tsx
- src/screens/Notifications/NotificationScreen.tsx
- src/screens/Notifications/UpdateEmailNotificationScreen.tsx
- src/screens/WalletDetailsScreen.tsx
- src/state/notifications/actions.ts
- src/state/notifications/reducer.ts
- src/state/notifications/sagas.ts
Call basic request (subscribe/unsubscribe/modify) before going to confirm screen so that allows handling error from basic requests on dedicated screens. Fixed loader buttons. Fixed deleting email with the unsubscribing flow.
> Confirm email refactor

- src/screens/Notifications/ChooseWalletsForNotificationScreen.tsx
- src/screens/Notifications/NotificationScreen.tsx
- src/state/notifications/selectors.ts
Fixing disappearing footer buttons on subscribed wallets list.
> subscribed wallet list fixed

- src/screens/Dashboard/DashboardScreen.tsx
- src/screens/ImportWalletScreen.tsx
- src/screens/RecoveryTransactionList/RecoveryTransactionListScreen.tsx
- src/screens/SendCoinsScreen.tsx
- src/state/wallets/selectors.ts
Shows transaction notes also on recovery screen to e2e tests
> transactions with notes on recovery screen

- loc/en.js
- src/components/GenericInputItem.tsx
- src/consts/models.tsx
- src/screens/ContactDetailsScreen.tsx
- src/screens/CreateContactScreen.tsx
- src/screens/EditTextScreen.tsx
Fix for
1. After adding a contact with only spaces in the name field and changing it later, the name is not saving
2. If we save a contact with space in from of the name, we don't have a prefix letter, contact is not in the right order (if we add a new contact with space " abc" for example, space is removing and everything is fine, but it's work differently while editing a contact)
> Bugfix able to save an address contact without name

- src/components/TimeoutButton.tsx
- src/screens/LocalConfirmNotificationCodeScreen.tsx
- src/screens/Notifications/ConfirmEmailScreen.tsx
- src/state/notifications/actions.ts
- src/state/notifications/reducer.ts
- src/state/notifications/selectors.ts
Still counting time remaining to let user press 'resend' when the app in the background.
> Resend counting also in background

- src/screens/WalletDetailsScreen.tsx
Fix bug with enabled subscribe email button after internet connection lost
- [+] Checked on iOS
- [+] Checked on Android
> Disable subscribe button when offline
